### ISSUE TITLE
Collection numbers off

### ISSUE THREAD

**Issue by darkzimpulse** [justrealmilk/dev2.braytech.org#12]
My collection numbers are all off, Example 0/20 ghost shells. Also maybe add the overall collection score out of the possible score.

**Comment by justrealmilk** [comment]
yeaaaah it's broken because it doesn't know how to handle redacted items or something. sadly i can only work on one thing at a time and i've currently got the clan page in pieces. it's like there's been a murder

it should rectify itself next wednesday
