### ISSUE TITLE
Clan XP missing

### ISSUE THREAD

**Issue by parnmatt** [justrealmilk/dev2.braytech.org#13]
It seems in a recent update, under the clan tab, you have replaced Clan XP with Crucible efficiency, Iron Banner efficiency, Gambit efficiency, Nightfalls cleared, and Raids cleared. This new information is very useful, especially as a clan owner; however I found the Clan XP quite helpful to know as well. Would it be possible to add that back into the interface?

**Comment by lyrad87** [comment]
@justrealmilk I hope this can serve as inspiration: [https://after8s.team/#stats](https://after8s.team/#stats). There is much more that you can show but we opted out to just include these stats.
