### ISSUE TITLE
Mobile (touch) support for the vendors page

### ISSUE THREAD

**Issue by jdeezie** [justrealmilk/dev2.braytech.org#17]
The detail overlay does not display when touching the options for any of the vendor info.

**Comment by justrealmilk** [comment]
Are you referring to the item tooltip?

**Comment by jdeezie** [comment]
yep. sorry i totally blanked on the proper name

**Comment by justrealmilk** [comment]
🤔 so like it doesn’t work on items on the vendor pages? What phone/browser

**Comment by jdeezie** [comment]
iPad with the latest version of iOS (12.1). I just checked my phone for the first time and you have it working there.

**Comment by justrealmilk** [comment]
Tablet usage is super low and I don’t have a test device (I have an iPad 2nd edition from 2010) so I don’t really test for it. 

I’ll do my best with the next version though. It’s a major update.
