### ISSUE TITLE
Feature request: ability to hide certain or re-order checklists

### ISSUE THREAD

**Issue by lyrad87** [justrealmilk/dev2.braytech.org#19]
On the checklists page, I'd love to be able to turn the individual lists on/off. Currently, I can only see the first five or the second five (on a widescreen monitor) but, for example, I'd like to be able to see the nodes, bones and eggs as they are the main ones I have to work on.

**Comment by justrealmilk** [comment]
If I even had time to use checklists, I might be able to empathise 😅 

I wouldn't even know where to start with the UI on this. If you have any suggestions, I'd appreciate it.

For now, this just isn't in my scope.

**Comment by lyrad87** [comment]
Could you not just make them hideable? That shouldn't be too difficult. Like how d2checklist.com does it. A simple solution that lets the users decide what he wants to focus on.
<img width="429" alt="bildschirmfoto 2018-12-12 um 08 39 17" src="https://user-images.githubusercontent.com/7974733/49854159-a0b19500-fde9-11e8-88fb-055c2b85750c.png">
