### ISSUE TITLE
December 2018

### ISSUE THREAD

**Issue by justrealmilk** [justrealmilk/dev2.braytech.org#22]
- [x] teach ServiceWorker to talk
- [x] credits page with footer link
- [ ] improved Vendors page UI
- [x] entirely new Clan page
- [x] expand _This Week_ to include Nightfalls and Flashpoints
- [x] multilingual
- [ ] pvp stats and modes
- [ ] show standing in stats

**Comment by koenigderluegner** [comment]
Got a few questions about "this week", what do you think will be the best approach to add more content like nightfall? pack them all 4 (or 3 if you don't want guided games) in 4 modules or in 1 module like checklists? Add pagination like checklists there to or just add them below/under the current content?

**Comment by justrealmilk** [comment]
I’m thinking 4 columns for desktop, where we shove EP somewhere else as it’s such a short list. 

I haven’t looked into flashpoints yet and if there’s many relevant triumphs but I’d say flashpoints would be in its own column with EP. 

Another column for scores nightfalls. Seems pointless to have the guided games option as you can’t achieve much there so I’ve already filtered it out. It’s in the latest push

**Comment by justrealmilk** [comment]
That's a good point. Is this one of those situations where I need to make a decisive decision?

**Comment by koenigderluegner** [comment]
Looks like it. Not including them would be a bit easier because they have different hashes than their non guided versions but if the guided game is different then the other 3 nightfalls you might miss out on something.

**Comment by justrealmilk** [comment]
I'm gonna say we exclude guided games. Besides, I'm the only person I know that uses them and the queue times are insane.

**Comment by koenigderluegner** [comment]
Alright, I'll see what I can do if you don't mind or have already started (except for that commit 14~ hours ago). 

I use guided games, too but as a duo, those queue times are ok but never saw one that really needed help just more fire power (which I don't mind because I do them for collectables and triumphs). Maybe I'm the only one that would "need" them on the list on braytech

**Comment by justrealmilk** [comment]
I mean, you can overrule my choice and remove the filter method from that line I wrote haha. See how it goes

**Comment by koenigderluegner** [comment]
In my local version I tested it with guided games, since they have different hashes I had to find a way to map them, so either map guided hash to non guided hash or use a slug, didn't like one of those solutions. For now I'll look into flashpoints and regular nightfalls.

**Comment by justrealmilk** [comment]
I thought they returned an activityHash just like the scored ones 🤔

**Comment by koenigderluegner** [comment]
Do they have the exact same one? I can check it in about an hour, don't have internet access on my laptop right now. I don't know why I tried those methods but I think there was something that stopped me from doing it "the easy way". Or maybe I just wasn't paying enough attention. :/ Will look into it.

**Comment by justrealmilk** [comment]
I'm fairly sure. It was 2am when I was console logging, but I'm fairly sure.

**Comment by koenigderluegner** [comment]
Ok, I checked what you were talking about and now I know what I wanted to say but did in a poor way. Another try: the activityHash for "The Corrupted" (non guided) is 3034843176 and "The Corrupted" (guided game) is 3447375316. So if we want to store triumphs and items in 'consolidatedInfo' like before we have to map the 2 hashes. Its easy to differentiate if its a guided game or not (as you already done this) but we need that small step to map them, except you got a better solution, but I haven't for now.

**Comment by justrealmilk** [comment]
Oh... Well what the heck. That's frustrating.

**Comment by koenigderluegner** [comment]
So, what do you think should we do now? 

The slug version I tried looks like this: 

```
nightfall: {
        "exodus-crash": {

          triumphs: [
            1526865549, // Exodus (Score)
            2140068897 // Faster than Lightning
          ],
          collectibles: [
            3036030067, // Impact Velocity
            3490589927, // Exodus Crash Emblem

          ]
        }, ...
```
easier to read but less reliable (if they make typos and fix them); no need for a second map but needs to call a slug function everytime

Or stick with the plan and exclude guided games

**Comment by koenigderluegner** [comment]
I can do that, if we map anyway, theres no need for a slug, we can just map guidedHash: scoredHash and get infos from consolidatedInfo like before, or am I missing something?   
  
Btw. do you know how to access emblem variants with your current system? [light.gg Emblem](https://www.light.gg/db/items/769740914/better-failsafe-than-sorry/) I tried to implement this before you reworked the views but had no time to check if afterwards. (I thought that's what items[] is for but instance items seem not to work)
