### ISSUE TITLE
Feature request: add links/locations to the Corrupted Eggs/Ahamkara Bones/Cat Statues checklists

### ISSUE THREAD

**Issue by lyrad87** [justrealmilk/dev2.braytech.org#23]
Similar to what you have for the nodes, it would be helpful to know where the missing eggs, bones or cat statues are. Maybe the API lets you know where they are **or** adding YouTube links to each could work as well but would require a lot of extra work. This might help out everyone who is chasing them.

Since you used lowlidev for the other checklists, you could for use it for those as well?

<img width="343" alt="bildschirmfoto 2018-12-12 um 08 53 12" src="https://user-images.githubusercontent.com/7974733/49854799-a6a87580-fdeb-11e8-9312-a2df9b7e50e2.png">

<img width="381" alt="bildschirmfoto 2018-12-12 um 08 54 45" src="https://user-images.githubusercontent.com/7974733/49854875-d6f01400-fdeb-11e8-8f30-05537a875b8d.png">

**Comment by koenigderluegner** [comment]
I added this part for cats and eggs in an earlier commit, tested them randomly but Tom found (at least) one that not correct on lowlidev so it's removed for now
