### ISSUE TITLE
Your API Key is visible?

### ISSUE THREAD

**Issue by robxu9** [justrealmilk/dev2.braytech.org#3]
It looks like you have an API key for bungie.net visible here? https://github.com/justrealmilk/dev2.braytech.org/blob/master/.env.production#L3

If so, you should consider it compromised and immediately revoke it.

**Comment by justrealmilk** [comment]
It's required, but thanks for your concern, traveller.

**Comment by robxu9** [comment]
If it is required, you should not keep it in a git repository that has been made public, and instead keep it on a separate system. The API key is essentially compromised, which is a security risk. (Though I would assume it has read permissions only, the problem is that people can impersonate you with the API key. Also, TOS.)
