### ISSUE TITLE
german translation

### ISSUE THREAD

**Issue by koenigderluegner** [justrealmilk/dev2.braytech.org#30]
I noticed that (at least) german translation is missing. I don't know if @marquesinijatinha just forgot to commit the file or if it's missing entirely. I can translate it if it's missing but just want to be sure it's not done, yet

**Comment by marquesinijatinha** [comment]
Hi Alexander, I forgot to add the 'de' package, but I didn't translate
anything, all language packs are English->English templates (except pt-BR,
that I did translate some parts when I was testing).
To translate to German you just need to duplicate the 'en' folder to a new
'de' and change the translation.json there.

Em sáb, 22 de dez de 2018 08:28, Alexander <notifications@github.com
escreveu:

**Comment by koenigderluegner** [comment]
Alright, I'll add a german translation, thanks for the answer

**Comment by justrealmilk** [comment]
<3
