### ISSUE TITLE
Site won't load

### ISSUE THREAD

**Issue by hotmeteor** [justrealmilk/dev2.braytech.org#32]
Just hit the site and it's not loading. Here's what dev tools has to say:

![screen shot 2018-12-22 at 5 15 23 pm](https://user-images.githubusercontent.com/378585/50379335-4399b880-060d-11e9-9ad2-1b351daf2634.png)

**Comment by hotmeteor** [comment]
Well, after I reported this I wondered if my Chrome was acting up. And then I ended up installing an OS update on my machine. :/

Once it’s done I’ll load it up again but this could be a false alarm. Sorry

**Comment by hotmeteor** [comment]
It was Chrome 70. Not sure if minor version

**Comment by hotmeteor** [comment]
It never got that far, was stuck at "Updating..."

All that said, it's loading now after a restart. Sorry for the noise.

**Comment by justrealmilk** [comment]
That's okay!
