### ISSUE TITLE
Play once Adventure line incomplete when done with multiple characters

### ISSUE THREAD

**Issue by brianp** [justrealmilk/dev2.braytech.org#5]
I noticed in my Adventures checklist I was missing a single Adventure. Which was weird. I did a little digging and found out these two adventures are the Saints 14 adventure, which can only be completed once across all characters. These are the only two adventures that are account bound.

The result is I did the "Not Even the Darkness" adventure on my Hunter and the "Signal Light" adventure on my Warlock. So when I'm looking at Braytech from my hunter it shows the adventure as incomplete, but it can never technically be completed again.

![image](https://user-images.githubusercontent.com/179134/48546990-ed2cb200-e8c9-11e8-9450-80e410d130d5.png)

I believe these two adventures need to be account bound, and not character bound. Although I understand the triumphs screen tends to show them in the same manner. So it is less of a bug, and more of a confusing piece of information which you could opt to fix. Although I'd understand if you don't, as it does match Bungie.

Cheers.

**Comment by justrealmilk** [comment]
I still haven't got around to this. Part of me wants to leave it as the API reports it, but part of me wants to opt to fix as you've suggested. Are the adventures definitely account bound in-game and it's entirely an API anomaly?

**Comment by etherealdi** [comment]
> I still haven't got around to this. Part of me wants to leave it as the API reports it, but part of me wants to opt to fix as you've suggested. Are the adventures definitely account bound in-game and it's entirely an API anomaly?

It's a known issue: https://www.reddit.com/r/DestinyTheGame/comments/8veqr9/where_are_signal_light_not_even_the_darkness/

**Comment by justrealmilk** [comment]
> > I still haven't got around to this. Part of me wants to leave it as the API reports it, but part of me wants to opt to fix as you've suggested. Are the adventures definitely account bound in-game and it's entirely an API anomaly?
> 
> It's a known issue: https://www.reddit.com/r/DestinyTheGame/comments/8veqr9/where_are_signal_light_not_even_the_darkness/

Known issue with those fine fellows but I don't see a Bungie replied badge anywhere 👀

**Comment by justrealmilk** [comment]
0.7.9 will show as complete on all characters if completed on any character
