### ISSUE TITLE
[Question] What are your API rules?

### ISSUE THREAD

**Issue by TheHandsomeCoder** [justrealmilk/dev2.braytech.org#6]
I saw a link to your xur api in a bungie thread went looking to see what your API rules/permissions are?

I'm making voice controls for my google assistant around to make playing the game a bit easier and would like to use it, but I don't want to use your API without permission and without knowing if you have rate limits etc

**Comment by justrealmilk** [comment]
My rules are don't break it 😄 

DM me somewhere if you need help with endpoint availability or if you're going to hit it particularly hard with requests
